// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WatchShop.DataAccess;

#nullable disable

namespace WatchShop.DataAccess.EF.Migrations
{
    [DbContext(typeof(WatchDbContext))]
    partial class WatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FeatureWatch", b =>
                {
                    b.Property<int>("FeaturesID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchesID")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeaturesID", "WatchesID");

                    b.HasIndex("WatchesID");

                    b.ToTable("FeatureWatch");
                });

            modelBuilder.Entity("WatchStore.DataAccess.Models.Feature", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("WatchStore.DataAccess.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Country = "Япония",
                            ManufacturerName = "Casio"
                        },
                        new
                        {
                            ID = 2,
                            Country = "Швейцария",
                            ManufacturerName = "Tissot"
                        },
                        new
                        {
                            ID = 3,
                            Country = "Швейцария",
                            ManufacturerName = "Rolex"
                        });
                });

            modelBuilder.Entity("WatchStore.DataAccess.Models.Stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("WatchID");

                    b.ToTable("Stock");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DeliveryDate = new DateTime(2023, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 50,
                            WatchID = 1
                        },
                        new
                        {
                            ID = 2,
                            DeliveryDate = new DateTime(2023, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 20,
                            WatchID = 2
                        },
                        new
                        {
                            ID = 3,
                            DeliveryDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 5,
                            WatchID = 3
                        });
                });

            modelBuilder.Entity("WatchStore.DataAccess.Models.Watch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("WatchModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WatchType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Watches");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ManufacturerID = 1,
                            Price = 12000m,
                            WatchModel = "G-Shock GA-2100",
                            WatchType = "кварцевые"
                        },
                        new
                        {
                            ID = 2,
                            ManufacturerID = 2,
                            Price = 45000m,
                            WatchModel = "T-Classic",
                            WatchType = "механические"
                        },
                        new
                        {
                            ID = 3,
                            ManufacturerID = 3,
                            Price = 850000m,
                            WatchModel = "Submariner",
                            WatchType = "механические"
                        });
                });

            modelBuilder.Entity("FeatureWatch", b =>
                {
                    b.HasOne("WatchStore.DataAccess.Models.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WatchStore.DataAccess.Models.Watch", null)
                        .WithMany()
                        .HasForeignKey("WatchesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WatchStore.DataAccess.Models.Stock", b =>
                {
                    b.HasOne("WatchStore.DataAccess.Models.Watch", "Watch")
                        .WithMany("StockEntries")
                        .HasForeignKey("WatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("WatchStore.DataAccess.Models.Watch", b =>
                {
                    b.HasOne("WatchStore.DataAccess.Models.Manufacturer", "Manufacturer")
                        .WithMany("Watches")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("WatchStore.DataAccess.Models.Manufacturer", b =>
                {
                    b.Navigation("Watches");
                });

            modelBuilder.Entity("WatchStore.DataAccess.Models.Watch", b =>
                {
                    b.Navigation("StockEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
